### PR TITLE
Fix some duplicate ringtones

### PR DESCRIPTION
**Pull request by bmos**

### CODE REVIEW

**Comment by bmos** [comment]
Is there something I need to do to get this looked at? It's a problem in so many ROMs I've used...

**Comment by jerdog** [comment]
Two things:
1. Submit issues at jira.omnirom.org
2. Verify you don't have those same ringtones on your sdcard

**Comment by bmos** [comment]
Oh, didn't realize omni has a separate system for submitting changes.
Thanks!

**Comment by bmos** [comment]
Looks like my pull request was rendered obsolete but someone.
https://gerrit.omnirom.org/#/c/4459/

**Pull request closed without merging**
